### ISSUE TITLE
Update JFoenix?

### ISSUE THREAD

**Issue by camdenorrb** [bkenn/KFoenix#1]
Why are y'all lagging behind version wise? 1.11.1 is out?

**Comment by bkenn** [comment]
It is a mistake. I was using a version used by another of my projects. I pushed a fix. You can target the latest build via 
```
repositories {
    maven { url "https://jitpack.io" }
}

dependencies { 
    compile 'com.github.bkenn:KFoenix:master-SNAPSHOT'
}
```
